### ISSUE TITLE
Feature req: Default SELF_URL

### ISSUE THREAD

**Issue by disconn3ct** [kucrut/ttrss-reader#2]
Is it possible to default SELF_URL to the current url's parent? (For example, if current url is "http://foo.baz.rz/ttrss/kucrut/" prepopulate the form with "http://foo.baz.rs/ttrss/".)

**Comment by 2vek** [comment]
Extending on this, I think SELF_URL auto detection can work by testing url one level up.

e.g. if ttrss-reader is hosted at
- http://example.com/foo/bar/,  try for http://example.com/foo/
- http://example.com/foo/, try for http://example.com
- http://foo.example.com/bar/, try for http://foo.example.com

If ttrss detected, Url should be auto filled, else Url text box is left blank at login prompt.

There can be an other ways like creating `config.json` in root of ttrss-reader which will be loaded at login screen to define default settings. e.g. [mdwiki](http://dynalon.github.io/mdwiki/#!index.md) does this.

**Comment by kucrut** [comment]
I don't think a detection logic needs to be added because:
- There are many variations of TTRSS' directory structure. For example I have mine structured as http://example.com/d (default UI) and http://example.com/r (this app).
- The detection will need to make API requests.
- You can even [use this app](http://kucrut.github.io/ttrss-reader/) without installing it on your server (if CORS is enabled).

**Comment by disconn3ct** [comment]
For the majority of cases it is likely to be a subdirectory on the main installation. Also, even if it isn't, defaulting would still make life easier - typing full urls on mobile is not especially convenient but in your /d and /r example, you would only have to type 'd'.
