### ISSUE TITLE
Add support to SINGLE_USER_MODE and Basic Authentication

### ISSUE THREAD

**Issue by atallo** [kucrut/ttrss-reader#7]
I use TTRSS in SINGLE_USER_MODE with Basic Authentication. I copy this ttrss-reader in my ttrss folder, but after login button said "autorization required".

Thanks!

**Comment by kulak** [comment]
I am a user (not developer) of this project and your problem is not entirely clear to me.

It sounds like you have a Basic Authentication configured at a web server level (that has nothing to do with ttrss-reader).  You log-into it 1st and then you have TTRSS-reader login prompt.  You provide your information (2nd time) and you shall be logged in.

I am not sure at which point in the login process you have a problem.  
Perhaps screenshots can help?

**Comment by atallo** [comment]
I test last version... and now work.

Thanks!
